[workspace]
resolver = "3"

members = [
    "bundle_status_service",
    "common",
    "config",
    "jito_fee_service",
    "jupiter_trader_data",
    "jupiter_trader_service",
    "price_service",
    # "stargate_service",
    "ws_price_service",
    # "encryptions-service",
    "wallet_models",
    "helius_data",
    "saturn-bundle-tracker",
    "saturn_errors",
    "user_session_manager",
]

exclude = [
    "saturn-wallet",
    "saturn-trader",
    "privat_vps",
    "bun_price_service"
]
