services:
  redis_main:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_main:/data

  redis_jito:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_jito:/data

  redis_notification:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_notification:/data

  redis_atl:
    image: redis:7-alpine
    ports:
      - "6382:6379"
    volumes:
      - redis_atl:/data

  bundle_status_service:
    build:
      context: .
      dockerfile: bundle_status_service/Dockerfile
    depends_on:
      - redis_main
      - redis_jito
      - redis_atl
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_main
      - JITO_TIP_REDIS_HOST=redis_jito
      - ATL_REDIS_HOST=redis_atl
      - RUST_BACKTRACE=1

  jito_tip_service:
    build:
      context: .
      dockerfile: jito_fee_service/Dockerfile
    depends_on:
      - redis_jito
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis_jito:6379
      - RUST_BACKTRACE=1

  # price_service:
  #   build:
  #     context: .
  #     dockerfile: price_service/Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     - RUST_BACKTRACE=1

volumes:
  redis_main:
  redis_jito:
  redis_atl:
