[package]
name = "jupiter_trader_service"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.41", features = ["serde"] }
reqwest = { version = "0.12.22", features = ["json"] }
redis = { version = "0.32.4", features = ["tokio-comp", "json"] } 
solana-sdk = "2.3.1"
common = { path = "../common" }
jupiter_trader_data = {path = "../jupiter_trader_data"}