[package]
name = "jupiter_trader_data"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
common = { path = "../common" }
proto_models = {path = "../proto_models"}
solana-sdk = "2.3.1"
