[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
saturn_errors = { path = "../saturn_errors" }
rustls = "0.22"
futures = "0.3.31"
tokio-tungstenite = { version = "0.21", features = ["connect", "rustls-tls-webpki-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
tokio = { version = "1.45.1", features = ["full", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.89"
reqwest = { version = "0.12.24", features = ["json"] }
governor = "0.10.2"
jito-sdk-rust = "0.3.2"
anyhow = "1.0"
