[package]
name = "encryptions-service"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = {version =  "0.5.3", features = ["password-hash"]}
chacha20poly1305 = "0.10.1"
bip39 = "2.2.0"
zeroize = "1.8.2"
hmac = "0.12.1"
sha2 = "0.10.9"
governor = "0.10.2"

config = {path = "../config"}
wallet_models = {path = "../wallet_models"}
chrono = { version = "0.4", features = ["serde"] }

tokio = { version = "1.45.1", features = ["full", "macros"] }
async-trait = "0.1.89"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

solana-sdk = "2.3.0"
solana-client = "2.3.7"
solana-account-decoder = "2.3.7"
spl-token = "8.0.0"
spl-token-interface = "1.0.0"